
import json
import collections

# Hardcoded prerequisites from complete_diagram.py
course_prerequisites = {
  "MATH461": ["CMSC250"],
  "CMSC216": ["CMSC132"],
  "CMSC330": ["CMSC216", "MATH461"],
  "CMSC351": ["CMSC216"],
  "CMSC320": ["MATH140", "STAT400"],
  "CMSC421": ["CMSC330"],
  "CMSC422": ["CMSC330", "CMSC351"],
  "CMSC426": ["CMSC330", "CMSC351", "MATH461"],
  "CMSC470": ["CMSC320", "CMSC330", "CMSC351", "MATH461"],
  "CMSC435": ["CMSC426"],
  "MATH401": ["CMSC330", "CMSC351", "MATH461"],
  "CMSC460": ["CMSC422"]
}

def main():
    try:
        with open("data/courses.json", "r") as f:
            courses_raw = json.load(f)
    except Exception as e:
        print(f"Error reading courses.json: {e}")
        return

    # Process courses into a simplified dictionary
    processed_courses = {}
    
    # We want a map of course_id -> details
    for c in courses_raw:
        cid = c.get("course_id")
        if not cid: continue
        
        processed_courses[cid] = {
            "id": cid,
            "name": c.get("name", ""),
            "credits": c.get("credits", "3"),
            "description": c.get("description", "")
        }

    # Verify that all prereq keys and value-items exist in catalog?
    # Not strictly necessary, but good to know.
    # The prompt says "output a single data.js... containing The Prerequisite Map".
    
    dropdown_options = [
      "MATH140",
      "MATH141",
      "STAT400",
      "CMSC131",
      "CMSC132",
      "CMSC216",
      "CMSC250",
      "CMSC330",
      "CMSC351",
      "CMSC320",
      "MATH461",
      "CMSC422",
      "CMSC426",
      "CMSC470",
      "CMSC435",
      "MATH401",
      "CMSC460"
    ]

    # Generate data.js content
    js_content = "// Auto-generated by export_data.py\n\n"
    
    js_content += f"const COURSE_CATALOG = {json.dumps(processed_courses, indent=2)};\n\n"
    js_content += f"const PREREQUISITE_RULES = {json.dumps(course_prerequisites, indent=2)};\n\n"
    js_content += f"const DROPDOWN_OPTIONS = {json.dumps(dropdown_options, indent=2)};\n"

    with open("data.js", "w") as f:
        f.write(js_content)
    
    print("Successfully generated data.js")

if __name__ == "__main__":
    main()
