import json
import collections

# Hardcoded prerequisites from complete_diagram.py
# Load prerequisites from JSON source instead of hardcoding
try:
    with open("data/sample-prerequisites.json", "r") as f:
        course_prerequisites = json.load(f)
except Exception as e:
    print(f"Warning: Could not load sample-prerequisites.json: {e}")
    course_prerequisites = {}

# Fallback basic prerequisites if not in the hardcoded list
# This is to support the "Build Your Own" flow where users might pick other courses
# But since the user specifically attached a screenshot with these specific courses,
# we should prioritize these.

def main():
    try:
        with open("data/courses.json", "r") as f:
            courses_raw = json.load(f)
    except Exception as e:
        print(f"Error reading courses.json: {e}")
        return

    # Process courses into a simplified dictionary
    processed_courses = {}
    for c in courses_raw:
        cid = c.get("course_id")
        if not cid: continue
        
        processed_courses[cid] = {
            "id": cid,
            "name": c.get("name", ""),
            "credits": c.get("credits", "3"),
            "description": c.get("description", ""),
            "base_prereqs": [] # We will populate this from the JSON relationships if needed, or just manual
        }

    # Generate data.js content
    js_content = "// Auto-generated by scripts/build_data.py\n\n"
    
    # 1. All Course Data (Minified for size if necessary, but 4MB is fine-ish. simplified is better)
    js_content += "const COURSE_CATALOG = " + json.dumps(processed_courses, indent=2) + ";\n\n"
    
    # 2. Hardcoded Prerequisite Rules
    js_content += "const PREREQUISITE_RULES = " + json.dumps(course_prerequisites, indent=2) + ";\n"

    # 3. Dropdown Options (Derived from all involved courses)
    all_involved_courses = set(course_prerequisites.keys())
    for prereqs in course_prerequisites.values():
        all_involved_courses.update(prereqs)
    
    js_content += "const DROPDOWN_OPTIONS = " + json.dumps(list(all_involved_courses), indent=2) + ";\n"

    with open("data.js", "w") as f:
        f.write(js_content)
    
    print("Successfully generated data.js")

if __name__ == "__main__":
    main()
